function results = calculateArea(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------
BW=createMask(im);
props=regionprops("table",BW,"Area");
areaPixels=sum



imgray = im2gray(im);

bw = imbinarize(imgray);

results.imgray = imgray;
results.bw     = bw;

%--------------------------------------------------------------------------
